channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=25.2
- pip:
  - mlflow==3.6.0
  - numpy==2.3.5
  - pandas==2.2.3
  - psutil==7.1.3
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - xgboost==3.0.2
name: mlflow-env
